In [2]:
import numpy as np


Why numpy(Numerical Python)? :- As a we know list is an alternative of array.
But when data science introduced then large number of data is being stored in list but time complexity of list is very high because list use dynamic and referential array concept.That's why numpy is introduced to solve this problem because it is memory efficient,used for working with array.A Numpy array is like special list in python with same data type.

So,we will create Array and deal with array in numpy.

In [3]:
# creation of an araay
arr = np.array([25,41,63,66,85,74])
arr

array([25, 41, 63, 66, 85, 74])

In [4]:
type(arr)
# ndarray -> n dimensional array

numpy.ndarray

In [5]:
arr.size  #no. of item

6

In [6]:
len(arr)

6

In [7]:
#  to check the dimension of array
arr.ndim

1

In [8]:
# to check data type of array
arr.dtype

dtype('int64')

In [9]:
print(np.__version__)

2.0.0


In [10]:
arr2 =np.array([25,41,63,66,85,74,'upflairs',True])  # make all data into string
arr2

array(['25', '41', '63', '66', '85', '74', 'upflairs', 'True'],
      dtype='<U21')

In [11]:
arr2.dtype

dtype('<U21')

In [12]:
print(arr2)

['25' '41' '63' '66' '85' '74' 'upflairs' 'True']


Indexing and slicing in this same as array as we learn earliar

In [13]:
# slicing is same as previous

print(arr[3])
print(arr[-1])
print(arr[2:5])
print(arr[:6]) # print from start
print(arr[2:])  # print till end
print(arr[2::2])  # jump is 2



66
74
[63 66 85]
[25 41 63 66 85 74]
[63 66 85 74]
[63 85]


In [14]:
arr[-1]=53

In [15]:
arr + 2 # add 2 in every element

array([27, 43, 65, 68, 87, 55])

Now let's consider 2 dimensional array(arrays under an array).It means there are several single dimension array in an array.

In [16]:
ls = [[1,2,3],[4,5,6],[7,8,9]]
type(ls)
print(ls[0][2])

3


In [17]:
arr3 = np.array(ls)  # here we convert list into array
print(arr3)
print(arr3.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [18]:
# find no. of rows and column
arr3.shape  #(row,column)

(3, 3)

Excessing in 2 dimensional array.

In [19]:
print(arr3[0])  #excessing single row
print(arr3[0][1])  #excessing a single element
print(arr3[2][2])

# excessing multiple rows
arr3[0:2]  # it will show 0th and 1st index row

# excessing multiple elements
# arr[row,column] -> [row start:row end,col start : col end]
print(arr[1:,1:])   # print 5,6,8,9

[1 2 3]
2
9


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
arr4 = np.random.randint(1,200,500)   #it will instant make array of 500 element from 1 to 200
arr4

array([160,   1, 144,  27,  65,  49, 157, 105, 145, 109, 127, 169,  50,
        34,  11,  77,  99, 147, 135, 175,  16, 127,  42,   8,   9,   3,
       189, 162,  98, 185,  61, 151, 115,  40,  48, 127, 193, 166, 158,
        58,  26,  85,  55,  81, 140,   3, 106,  32, 184, 199,  51,  63,
       194, 108,  94, 100, 115, 196, 119,  51, 197, 158, 138, 102, 181,
       106,  42, 193,  33,  71,  73, 102,  69, 167, 127, 164, 188,  23,
       122,  64,  79, 173, 187, 107,   6, 194,  19,   1,  49, 144,  98,
       173,  65, 115,  12, 155,  92,  82,   7,  75,  71,   1, 193,  75,
        96, 124, 178, 129,  21,  13, 177, 112, 176,  92,  94,  11, 167,
       144, 144,  53,  11,  16,  71, 108,  80,  99, 170, 125,  97, 139,
       131,  92,  87, 180, 105,  39,  93,  21, 116, 176,  49,  15, 195,
        51, 112, 101,  88, 106, 196, 181,  30,   1, 140, 139,  67, 199,
       181, 128, 191, 110, 161, 166,  30, 155, 127, 138,  50,  36,  13,
       153,  61,  66,  15,  75, 176,  40,  26,  71,  67,   2, 19

In [ ]:
# arr filter all those items that are less than equal to 100
# count =0
# for item in arr4 :
#   if (item<100 or item == 100) :
#     count+=1
# print(count)

# or we can do that

arr4<=100  # give true and false in array
arr4[arr4<=100]  #filter above arr4 which have true
arr4[arr4<=100].size

246

In [ ]:
len(arr4[arr4<=100])

246

creating 2 D random array

In [ ]:
arr2 = np.random.randint(1,200,(10,6))
arr2

array([[ 62, 117,  81, 118,  99, 106],
       [ 57, 190,  46, 194,  76,  80],
       [ 89, 180, 123,   8,  26, 123],
       [134,  57, 193, 172, 116, 154],
       [190, 198, 116,  51,  21, 185],
       [138, 143, 116, 124,  42, 190],
       [172,  31,  67, 191, 145,  71],
       [ 95, 193, 120, 105,  94,  51],
       [  9, 195, 104, 145,  18,  81],
       [158, 194,  25, 144, 105, 141]], dtype=int32)

creating random 3 d array

In [ ]:
arr2 = np.random.randint(1,200,(10,6,3))
arr2

array([[[176,  34,  81],
        [118, 148, 177],
        [  9, 145,  66],
        [ 81, 111, 100],
        [158,  74,  98],
        [ 15,   9, 187]],

       [[ 52,  34,   2],
        [ 15, 190,   3],
        [ 83, 146,  92],
        [ 90,  51, 190],
        [ 35,  60,  51],
        [ 64, 127,  27]],

       [[129,  90,   6],
        [192, 173, 139],
        [116,  65, 176],
        [177, 195,  18],
        [ 97, 127, 170],
        [150, 186, 142]],

       [[154,  60, 182],
        [125, 184, 167],
        [110, 199, 126],
        [114, 118, 197],
        [ 13, 180,  12],
        [142,  37,  89]],

       [[108,  60,   6],
        [  3,  33, 150],
        [ 77,  60,  55],
        [161, 184, 110],
        [164, 150,  96],
        [166, 193,  19]],

       [[ 75, 134,  53],
        [ 59,   7, 150],
        [  6, 123,  10],
        [129, 127, 122],
        [194, 139, 155],
        [ 71, 157,  68]],

       [[ 98, 105, 165],
        [  2, 188, 170],
        [114, 101,  35],
        [ 63,

In [ ]:
arr = np.zeros(10)  #single dimensional array with 10 element having 0 value
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((10,5))   #2 d array
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones(10)
arr1 = np.ones((10,5))

In [ ]:
ls = list(range(0,10))   #creating a list in a range
ls

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
# arange create only single dimension array
arr = np.arange(60)  #creating an array in a range
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

If we want to convert 1D into 2D array then we have to decide no. of rows and column

In [ ]:
arr = arr.reshape(10,6)
# arr.reshape(10,7)  # can't divide 60 element into 10,7
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

DAY 2 OF NUMPY

Creation of 3D array

In [ ]:
# Creation of 3D array
# arr = [2D,2D,2D,2D....]
# these are lists given below,not actual array
arr1D = [1,2,3]
arr2D = [[1,2,3],[1,2,3],[1,2,3]]
arr3D = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]

In [ ]:
arr = np.array(arr3D)

In [20]:
arr3 = np.random.randint(1,200,(3,5,3))
arr3
# (table no. =3 , rows no.=5 , column no.=3)

array([[[170, 156, 141],
        [  2, 151, 124],
        [110, 107, 172],
        [170,  84,  22],
        [ 60,  11,  94]],

       [[  5,  28,  64],
        [170, 116,  93],
        [ 61,  99, 164],
        [133,  69,  66],
        [ 64, 188, 195]],

       [[ 55, 102,  56],
        [  1, 136,  89],
        [145,  80, 165],
        [117,  91, 192],
        [ 82,  28,  28]]], dtype=int32)

In [21]:
arr3.shape

(3, 5, 3)

Indexing of 3 dimension array :-
indexing --> arr[table,row,column],
             arr[table-start:end,row-start:end,column-start:end]

In [24]:
arr3[1,4,0:]
arr3[2,:2,1:]

array([[102,  56],
       [136,  89]], dtype=int32)

In [25]:
arr3[:,1,:]  #accessing first row of every table

array([[  2, 151, 124],
       [170, 116,  93],
       [  1, 136,  89]], dtype=int32)

Some functionalaty of numpy

In [28]:
arr = np.array([9,7,8])

In [30]:
# minimum of array
min(arr)

# maximum of array
max(arr)

np.int64(9)

In [29]:
# mean of array
np.mean(arr)

# sum of array
np.sum(arr)

np.int64(24)

In [32]:
# index of minimum element
np.argmin(arr)  

# index of maximum element
np.argmax(arr)

np.int64(0)

In [35]:
# sorting of array
arr.sort()   #ascending order
arr

array([7, 8, 9])

In [36]:
arr[::-1]  #descending order

array([9, 8, 7])

So till now we learn accessing , manipulating an 1d,2d,3d array.
creating instant array and sum functions like min,max,sum,mean,sort,argmin,argmax etc.